-- The 0016 policy let any authenticated user insert ANY single_use=true
-- discount code, not just gift codes generated by the gift-card purchase
-- flow — single_use alone isn't a reliable signal of "this is a gift
-- card code". Add an explicit is_gift_code flag and scope the staff
-- self-issue policy to single_use AND is_gift_code, so front desk can
-- only self-issue gift-redemption codes, not arbitrary single-use
-- discounts. Regular discount code management stays admin/owner-only
-- (existing policies from 0004).

alter table discount_codes add column if not exists is_gift_code boolean not null default false;

drop policy if exists "authenticated insert single-use discount codes" on discount_codes;

create policy "authenticated insert gift discount codes" on discount_codes
  for insert to authenticated
  with check (single_use = true and is_gift_code = true);
